############################
## CHANGE THESE
############################

baseURL: 'https://darrylgibbs.github.io/blog'
title: blog

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


